Attempt to fix the connection refused issue
Terraform cloud run failed because of
module.eks.kubernetes_config_map.aws_auth[0]: Creating...

Error: Post "http://localhost/api/v1/namespaces/kube-system/configmaps": dial tcp 127.0.0.1:80: connect: connection refused

  on .terraform/modules/eks/terraform-aws-eks-12.1.0/aws_auth.tf line 64, in resource "kubernetes_config_map" "aws_auth":
  64: resource "kubernetes_config_map" "aws_auth" {

Following this proposal:
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/817#issuecomment-624744793
to see if it fixes the error